name: Deploy Frontend Prefeitura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build e push da imagem
        run: |
          docker build -t devnardi/web-prefeitura:latest .
          docker push devnardi/web-prefeitura:latest

      - name: Atualizar container rodando
        run: |
          echo "Removendo container antigo..."
          docker rm -f web-prefeitura || true

          echo "Atualizando imagem..."
          docker pull devnardi/web-prefeitura:latest

          echo "Subindo novo container..."
          docker run -d \
            --name web-prefeitura \
            -p 3000:3000 \
            -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            devnardi/web-prefeitura:latest
