name: Deploy Backend Prefeitura

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout do c√≥digo
              uses: actions/checkout@v4

            - name: Login no Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

            - name: Build e push da imagem
              run: |
                  docker build -t devnardi/back-prefeitura:latest .
                  docker push devnardi/back-prefeitura:latest

            - name: Atualizar container rodando
              run: |
                  docker pull devnardi/back-prefeitura:latest
                  docker stop back-prefeitura || true
                  docker rm back-prefeitura || true
                  docker run -d --name back-prefeitura -p 4000:4000 devnardi/back-prefeitura:latest
